package com.apps.bean;

public class Dorm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dorm.dor_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String dorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dorm.dor_qua
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String dorQua;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dorm.dor_cost
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private Double dorCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dorm.dor_num
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private Integer dorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dorm.dor_in_num
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private Integer dorInNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dorm.dor_houid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String dorHouid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dorm.dor_id
     *
     * @return the value of dorm.dor_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getDorId() {
        return dorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dorm.dor_id
     *
     * @param dorId the value for dorm.dor_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDorId(String dorId) {
        this.dorId = dorId == null ? null : dorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dorm.dor_qua
     *
     * @return the value of dorm.dor_qua
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getDorQua() {
        return dorQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dorm.dor_qua
     *
     * @param dorQua the value for dorm.dor_qua
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDorQua(String dorQua) {
        this.dorQua = dorQua == null ? null : dorQua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dorm.dor_cost
     *
     * @return the value of dorm.dor_cost
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public Double getDorCost() {
        return dorCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dorm.dor_cost
     *
     * @param dorCost the value for dorm.dor_cost
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDorCost(Double dorCost) {
        this.dorCost = dorCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dorm.dor_num
     *
     * @return the value of dorm.dor_num
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public Integer getDorNum() {
        return dorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dorm.dor_num
     *
     * @param dorNum the value for dorm.dor_num
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDorNum(Integer dorNum) {
        this.dorNum = dorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dorm.dor_in_num
     *
     * @return the value of dorm.dor_in_num
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public Integer getDorInNum() {
        return dorInNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dorm.dor_in_num
     *
     * @param dorInNum the value for dorm.dor_in_num
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDorInNum(Integer dorInNum) {
        this.dorInNum = dorInNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dorm.dor_houid
     *
     * @return the value of dorm.dor_houid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getDorHouid() {
        return dorHouid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dorm.dor_houid
     *
     * @param dorHouid the value for dorm.dor_houid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDorHouid(String dorHouid) {
        this.dorHouid = dorHouid == null ? null : dorHouid.trim();
    }
}