package com.apps.bean;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_gender
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String stuGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.in_date
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private Date inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.depar
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String depar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clazz
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_houid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String stuHouid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_dorid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String stuDorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bed_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String bedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.in_out
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String inOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_phone
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    private String stuPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_gender
     *
     * @return the value of student.stu_gender
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_gender
     *
     * @param stuGender the value for student.stu_gender
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.in_date
     *
     * @return the value of student.in_date
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.in_date
     *
     * @param inDate the value for student.in_date
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.depar
     *
     * @return the value of student.depar
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getDepar() {
        return depar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.depar
     *
     * @param depar the value for student.depar
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setDepar(String depar) {
        this.depar = depar == null ? null : depar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clazz
     *
     * @return the value of student.clazz
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clazz
     *
     * @param clazz the value for student.clazz
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_houid
     *
     * @return the value of student.stu_houid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getStuHouid() {
        return stuHouid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_houid
     *
     * @param stuHouid the value for student.stu_houid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setStuHouid(String stuHouid) {
        this.stuHouid = stuHouid == null ? null : stuHouid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_dorid
     *
     * @return the value of student.stu_dorid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getStuDorid() {
        return stuDorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_dorid
     *
     * @param stuDorid the value for student.stu_dorid
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setStuDorid(String stuDorid) {
        this.stuDorid = stuDorid == null ? null : stuDorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bed_id
     *
     * @return the value of student.bed_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getBedId() {
        return bedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bed_id
     *
     * @param bedId the value for student.bed_id
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setBedId(String bedId) {
        this.bedId = bedId == null ? null : bedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.in_out
     *
     * @return the value of student.in_out
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getInOut() {
        return inOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.in_out
     *
     * @param inOut the value for student.in_out
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setInOut(String inOut) {
        this.inOut = inOut == null ? null : inOut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_phone
     *
     * @return the value of student.stu_phone
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_phone
     *
     * @param stuPhone the value for student.stu_phone
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }
}