package com.apps.dao;

import com.apps.bean.Dorm;
import com.apps.bean.DormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    long countByExample(DormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int deleteByExample(DormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int deleteByPrimaryKey(String dorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int insert(Dorm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int insertSelective(Dorm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    List<Dorm> selectByExample(DormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    Dorm selectByPrimaryKey(String dorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dorm record, @Param("example") DormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByExample(@Param("record") Dorm record, @Param("example") DormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByPrimaryKeySelective(Dorm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByPrimaryKey(Dorm record);
}