package com.apps.dao;

import com.apps.bean.House;
import com.apps.bean.HouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    long countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int deleteByPrimaryKey(String houId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    House selectByPrimaryKey(String houId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Mar 05 18:28:22 CST 2020
     */
    int updateByPrimaryKey(House record);
}